Hw04
AntonTymchenko/nodejs-homework-rest-api pull request #3
Opened 2021-11-15 13:01 UTC by AntonTymchenko

2021-11-15 19:52 UTC, KirillKulakow commented on controllers/getAllContacts.js
> +  const { page, limit } = req.query
если query параметров нет будет ошибка - сделать проверку
сделать преобразование этих параметров в число
сделать проверку на то что page и limit точно число

2021-11-15 19:55 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
если я буду не авторизован и сделаю запрос на контакты - будет ошибка

2021-11-15 19:57 UTC, KirillKulakow commented on middlewares/authenticate.js
> +        throw new NotFound('User not found')
какая разница какую ошибку ты тут ставишь, если в catch ты ее перезаписываешь на Unauthorized

2021-11-15 20:01 UTC, KirillKulakow commented on routes/api/auth.js
> +router.post(
не хватает одного пути users/current

2021-11-15 20:02 UTC, KirillKulakow requested changes
Need fix

2021-11-16 16:15 UTC, AntonTymchenko commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
я уже так запутался, что тут конкретно нужно сделать ?

2021-11-16 20:08 UTC, KirillKulakow commented on controllers/getAllContacts.js
> +  if (req.query) {
плохая проверка
если никаких параметров в query нет - будет пустой обьект, который пройдет эту проверку
проверяй конкретные параметры page и limit

2021-11-16 20:11 UTC, KirillKulakow commented on controllers/getAllContacts.js
> +  if (typeof page !== 'number' && typeof limit !== 'number') {
тоже плохая проверка
если я буду преобразовывать что либо (некорректное) в число, в ответ получу NaN
NaN - это число)

2021-11-16 20:13 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
если я не авторизированый пользователь - то в headers нет ключа authorization и при выполнении кода у тебя будет ошибка
сделай перед этой строкой сначала проверку на то что в headers есть ключ authorization а его значение это строка

2021-11-16 20:14 UTC, KirillKulakow requested changes
Need fix

2021-11-17 19:45 UTC, KirillKulakow commented on controllers/getAllContacts.js
> +  if (req.query.page && req.query.limit) {
очень плохой вариант - удалить

2021-11-17 19:46 UTC, KirillKulakow commented on controllers/getAllContacts.js
> +  let { page, limit } = req.query
здесь написать 
`let { page = 1, limit = 20 } = req.query`

2021-11-17 19:51 UTC, KirillKulakow commented on controllers/getAllContacts.js
> +  if (
ужасная проверка - переписать
`if (Number.isNaN(page) || Number.isNaN(limit)) {
  throw new BadRequest()
}`

2021-11-17 19:52 UTC, KirillKulakow commented on middlewares/authenticate.js
> +      return null
почему null?

2021-11-17 19:54 UTC, KirillKulakow requested changes
Need fix

2021-11-18 18:36 UTC, KirillKulakow approved these changes

2021-11-20 18:41 UTC, merged